import { Inter } from "next/font/google";
import "./globals.css";
// import "@/assets/helper.css"
// import { AntdRegistry } from '@ant-design/nextjs-registry';
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Authentication App",
  description: "Generated by Devminds",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
      {/*<AntdRegistry>*/}
        {children}
      {/*</AntdRegistry>*/}
      </body>
      </html>
  );
}
